project:
  type: website
  output-dir: docs

website:
  title: "Heitor C. Sousa"
  google-analytics: "G-FSNLDZW8VR"
  site-url: "https://heitorcsousa.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - sidebar:research
      - href: publications.qmd
        text: "Publications | Publicações"
        target: _blank
      - href: curriculum.qmd
        text: "CV"
        target: _blank
      - href: products.qmd
        text: "Products | Produtos"
        target: _blank
      - href: alteroikos.qmd
        text: "AlterOikos"
        target: _blank

  sidebar:
    - id: research
      title: "Research | Pesquisa"
      style: "docked"
      collapse-level: 2
      href: research.qmd
      target: _blank
      contents:
        - demography.qmd
        - community.qmd
        - fire.qmd
        - climchange.qmd
        - zoology.qmd
        - social.qmd
  page-navigation: true
  back-to-top-navigation: true
  page-footer: "Copyright 2025, Heitor C. Sousa"

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    includes:
       in_header: google_analytics.html

editor: visual
filters:
    - openlinksinnewpage

babelquarto:
  languagelinks: navbar
  languagecodes:
  - name: pt-BR
    text: "Português(BR)"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['pt-BR']
title-pt-BR: Heitor C. Sousa
description-pt-BR: description in pt-BR
author-pt-BR: author in pt-BR
lang: en
