---
title: "Publications"
format: html
website:
  template: jolla
bibliography: references.bib
---

Here is a list of my publications in cronological order. Click on each citation to view the complete reference.

| Citation | Topic | Type | Contribution |
|----|----|----|----|
| @sousa2025 | Social Conservation & Pyrogeography | Article | First-author |
| @desousa2024 | Biodemography & Pyrogeography | Article | First-author |
| @RN11618 | Biogeography & Zoology | Book chapter | Last-author |
| @c.sousa2023 | Social Conservation | Article | First-author |
| @RN11617 | Social Conservation | Book chapter | Co-author |
| @simoncini2022 | Biodemography & Climate change | Article | Co-author |
| @gonçalveskagueiama2022 | Climate change & Zoology | Article | Co-author |
| @RN11619 | Social Conservation | Book chapter | First-author |
| @ataídes2021 | Biodemography & Climate change | Article | Co-author |
| @costa2019 | Zoology & Pyrogeography | Article | Co-author |
| @colli2019 | Zoology | Article | Last-author |
| @sousa2016 | Biodemography & Zoology | Article | First-author |
| @sousa2015 | Biodemography & Pyrogeography | Article | First-author |
| @morais2014 | Zoology | Article | Co-author |

: Articles in cronological order

\
Below, you will find the full references in alphabetical order. If you want access to the full publications, please go to my [ResearchGate profile](https://www.researchgate.net/profile/Heitor-Campos-De-Sousa) or send me an e-mail ([heitorsousa.bio\@gmail.com](mailto:heitorsousa.bio@gmail.com)).
